FROM golang:1.26.8-trixie@sha256:771f3162219f7a66bb6be3fea1ba31f418932946a99ad9eac26ffd555dfcf393
ENV CGO_ENABLED 0

RUN apt-get update && apt-get install -y --no-install-recommends inotify-tools psmisc
RUN go install github.com/go-delve/delve/cmd/dlv@latest

COPY script/debug-entrypoint.sh /entrypoint.sh

VOLUME /dockerdev

WORKDIR /dockerdev

ENV DELVE_PORT 40000
ENV SERVICE_NAME service

EXPOSE 8000 $DELVE_PORT

ENTRYPOINT ["/entrypoint.sh"]
